/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as AnimeSourceIdAnimeIdRouteImport } from './routes/anime.$sourceId.$animeId'
import { Route as WatchSourceIdAnimeIdGroupIdEpisodeIdRouteImport } from './routes/watch.$sourceId.$animeId.$groupId.$episodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeSourceIdAnimeIdRoute = AnimeSourceIdAnimeIdRouteImport.update({
  id: '/anime/$sourceId/$animeId',
  path: '/anime/$sourceId/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSourceIdAnimeIdGroupIdEpisodeIdRoute =
  WatchSourceIdAnimeIdGroupIdEpisodeIdRouteImport.update({
    id: '/watch/$sourceId/$animeId/$groupId/$episodeId',
    path: '/watch/$sourceId/$animeId/$groupId/$episodeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/downloads': typeof DownloadsRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/anime/$sourceId/$animeId': typeof AnimeSourceIdAnimeIdRoute
  '/watch/$sourceId/$animeId/$groupId/$episodeId': typeof WatchSourceIdAnimeIdGroupIdEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/downloads': typeof DownloadsRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/anime/$sourceId/$animeId': typeof AnimeSourceIdAnimeIdRoute
  '/watch/$sourceId/$animeId/$groupId/$episodeId': typeof WatchSourceIdAnimeIdGroupIdEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/downloads': typeof DownloadsRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/anime/$sourceId/$animeId': typeof AnimeSourceIdAnimeIdRoute
  '/watch/$sourceId/$animeId/$groupId/$episodeId': typeof WatchSourceIdAnimeIdGroupIdEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/downloads'
    | '/history'
    | '/library'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sources'
    | '/anime/$sourceId/$animeId'
    | '/watch/$sourceId/$animeId/$groupId/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/downloads'
    | '/history'
    | '/library'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sources'
    | '/anime/$sourceId/$animeId'
    | '/watch/$sourceId/$animeId/$groupId/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/downloads'
    | '/history'
    | '/library'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sources'
    | '/anime/$sourceId/$animeId'
    | '/watch/$sourceId/$animeId/$groupId/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  DownloadsRoute: typeof DownloadsRoute
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  AnimeSourceIdAnimeIdRoute: typeof AnimeSourceIdAnimeIdRoute
  WatchSourceIdAnimeIdGroupIdEpisodeIdRoute: typeof WatchSourceIdAnimeIdGroupIdEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$sourceId/$animeId': {
      id: '/anime/$sourceId/$animeId'
      path: '/anime/$sourceId/$animeId'
      fullPath: '/anime/$sourceId/$animeId'
      preLoaderRoute: typeof AnimeSourceIdAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$sourceId/$animeId/$groupId/$episodeId': {
      id: '/watch/$sourceId/$animeId/$groupId/$episodeId'
      path: '/watch/$sourceId/$animeId/$groupId/$episodeId'
      fullPath: '/watch/$sourceId/$animeId/$groupId/$episodeId'
      preLoaderRoute: typeof WatchSourceIdAnimeIdGroupIdEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  DownloadsRoute: DownloadsRoute,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  AnimeSourceIdAnimeIdRoute: AnimeSourceIdAnimeIdRoute,
  WatchSourceIdAnimeIdGroupIdEpisodeIdRoute:
    WatchSourceIdAnimeIdGroupIdEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
