import { describe, expect, it } from "vitest";
import vectors from "@shared/profileRules.vectors.json";
import { vectorDaysToSeries, vectorEntriesToLibrary } from "@shared/profileRules";
import { computeAchievements } from "./achievements";
import { computeLevelProgress, totalXpEarned } from "./levelProgress";
import { computeStreaks } from "@/components/StreakBadge";

/**
 * Holds this implementation to the shared statement of the profile rules
 * (src/shared/profileRules.vectors.json, regenerated by scripts/generateProfileVectors.ts).
 *
 * XP, levels, achievement tiers and streaks are about to exist twice - here in TypeScript and in
 * Kotlin on Android - and two implementations of the same arithmetic drift silently: the same
 * watch history becomes level 7 on the desktop and level 6 on the phone, with nothing to point at.
 * The vectors are the thing to point at, and the Android port is meant to run against this exact
 * file.
 *
 * A failure here means one of two things: a rule changed on purpose, in which case regenerate the
 * vectors and review that diff as part of the change - or it changed by accident, which is the
 * whole point.
 */
describe("profile rules match the shared vectors", () => {
  it("covers every family and both ends of each tier", () => {
    // A guard on the vectors themselves: they are only worth anything while they still exercise
    // the rules, and a family added later with no case would otherwise pass unnoticed.
    const families = new Set(vectors.cases.flatMap((c) => c.expect.achievements.map((a) => a.id)));
    expect([...families].sort()).toEqual(
      ["collector", "episodes", "finisher", "first_title", "genres", "streak", "watch"],
    );
    expect(vectors.cases.length).toBeGreaterThanOrEqual(15);
    expect(vectors.streakCases.length).toBeGreaterThanOrEqual(6);
  });

  for (const testCase of vectors.cases) {
    it(`achievements and level: ${testCase.name}`, () => {
      const achievements = computeAchievements({
        entries: vectorEntriesToLibrary(testCase.input.entries),
        lifetimeWatchedMs: testCase.input.lifetimeWatchedMs,
        bestStreak: testCase.input.bestStreak,
      });

      expect(
        achievements.map((a) => ({
          id: a.id,
          current: a.current,
          target: a.target,
          unlocked: a.unlocked,
          level: a.level,
          maxLevel: a.maxLevel,
          xpReward: a.xpReward,
          xpEarned: a.xpEarned,
        })),
      ).toEqual(testCase.expect.achievements);

      const totalXp = totalXpEarned(achievements, testCase.input.lifetimeWatchedMs);
      expect(totalXp).toBe(testCase.expect.totalXp);

      const progress = computeLevelProgress(totalXp);
      expect(progress.level).toBe(testCase.expect.level);
      expect(progress.xpIntoLevel).toBe(testCase.expect.xpIntoLevel);
      expect(progress.xpForLevel).toBe(testCase.expect.xpForLevel);
    });
  }

  for (const streakCase of vectors.streakCases) {
    it(`streak: ${streakCase.name}`, () => {
      expect(computeStreaks(vectorDaysToSeries(streakCase.days))).toEqual(streakCase.expect);
    });
  }
});
